"""init

Revision ID: 7338fa08855c
Revises: 
Create Date: 2026-07-03 16:04:44.733415+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7338fa08855c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__employees'))
    )
    op.create_index(op.f('ix__employees__first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix__employees__id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix__employees__last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix__employees__phone'), 'employees', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__employees__phone'), table_name='employees')
    op.drop_index(op.f('ix__employees__last_name'), table_name='employees')
    op.drop_index(op.f('ix__employees__id'), table_name='employees')
    op.drop_index(op.f('ix__employees__first_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
